### ISSUE TITLE
B.B.Link Configurator Update Firmware Link

### ISSUE THREAD

**Issue by giminok** [islandmagic/bb-link#5]
In B.B.LinkConfigurator app - it shows the Firmware Version as 0.7.3.  The "Update Firmware" link is active below it.  

When "Update Firmware" link is pressed, the dialog shows "Update Firmware to 0.7.2".  

As it shows the adapter is on 0.7.3 the firmware update isn't needed so Update Firmware link should be disabled?   Only adding this if that can cause a problem otherwise do not think it matters once a radio is paired.

![BBL1](https://github.com/islandmagic/bb-link/assets/25875291/643aae15-8871-4ad9-a349-bf1fea85e444)
![BBL2](https://github.com/islandmagic/bb-link/assets/25875291/d4e86b89-aac3-48fa-b80e-edd1d53455bb)

**Comment by georges** [comment]
Thanks for the detailed report. There are a few things at play here.

0. The current OTA firmware is set to 0.7.2

1. There is a toggle in Settings -> B.B. Link Configurator -> Experimental that allows you to toggle a Beta channel for firmware updates. The Beta channel will post pre-release version as they are being tested. This allows me to test OTA update without disrupting anything. Usually that channel will have one version up, for instance now it's 0.7.3

2. Because of the Beta channel, I wanted a way to allow downgrade to released firmware. For example someone may try the Beta channel, realize it's breaking something and need to go back down. As such, I decided to allow firmware upgrade as long as the installed version is different than the available OTA version (could be upgrade or downgrade)

I could clean up the UI to be a more descriptive to inform the user they will downgrade in that case.

**Comment by georges** [comment]
And to answer the rest of your question, firmware upgrade should not affect radio pairing, unless of course some new code gets introduce that would require a repairing for some reason.

**Comment by giminok** [comment]
@georges Thank you for a quick reply.  The downgrade makes a lot of sense.  Appreciate the details.
